### ISSUE TITLE
 Playground doesn't work in the console due to a TypeError

### ISSUE THREAD

**Issue by gvozdvmozgu** [quarylabs/sqruff#1053]
The playground is not working in the console. Here's the error log:

```
index-DNlMWlVh.js:49 Uncaught TypeError: Cannot read properties of undefined (reading 'S')
    at Xhe (index-DNlMWlVh.js:49:42584)
    at Qhe (index-DNlMWlVh.js:50:34162)
    at index-DNlMWlVh.js:50:34187
```

**Comment by benfdking** [comment]
Thanks for raising 🙏 , has been fixed with a test to prevent in the future.
