### ISSUE TITLE
[Bug]: Error: Cannot find module 'vscode-languageclient/node'

### ISSUE THREAD

**Issue by mrufsvold** [quarylabs/sqruff#1068]
### What happened?

I installed the extension in VSCode, and got the following error in the Extension Host Output:

```
2024-12-17 12:28:38.471 [info] ExtensionService#_doActivateExtension Quary.sqruff, startup: false, activationEvent: 'onLanguage:sql'
2024-12-17 12:28:38.476 [error] Activating extension Quary.sqruff failed due to an error:
2024-12-17 12:28:38.476 [error] Error: Cannot find module 'vscode-languageclient/node'
Require stack:
- c:\Users\mrufsvold\.vscode\extensions\quary.sqruff-0.21.11\dist\native.cjs
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at Function.n._resolveFilename (node:electron/js2c/utility_init:2:16068)
    at Function.t._resolveFilename (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22715)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at Function.c._load (node:electron/js2c/node_init:2:16955)
    at Function.e._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10900)
    at Function.t._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
    at Function.i._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at Module.require (c:\Users\mrufsvold\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:195:34657)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (c:\Users\mrufsvold\.vscode\extensions\quary.sqruff-0.21.11\dist\native.cjs:1:682)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at Function.c._load (node:electron/js2c/node_init:2:16955)
    at Function.e._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10900)
    at Function.t._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
    at Function.i._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at Module.require (c:\Users\mrufsvold\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:195:34657)
    at require (node:internal/modules/helpers:179:18)
    at z_.xb (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23753)
    at async Promise.all (index 0)
```

### Version

sqruff - 0.21.11
vscode - 1.95.3

### Checked in Playground

- [ ] I have checked this bug in the [playground](https://playground.quary.dev/?secondary=Format).

**Comment by spence** [comment]
having this same issue

**Comment by MiniaczQ** [comment]
Seems to be a packaging issue?

https://github.com/microsoft/vscode/issues/30225

**Comment by benfdking** [comment]
Fixed in the latest release, please reopen if you find this is still an issue.
