### ISSUE TITLE
Getting Error "not implemented" when running sqruff lint

### ISSUE THREAD

**Issue by ikhudur** [quarylabs/sqruff#331]
Hello,

I have just installed sqruff by following the README.md file https://github.com/quarylabs/sqruff/blob/c2850ab65f350932612a1cd5c5d89d255f3da81f/README.md#linux

When I run sqruff lint <path-to-filename> I get the following error:

`thread 'main' panicked at crates/lib/src/core/config.rs:471:25:`
`not implemented`
`note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`

Could you please help me with this?

More info:
I use WSL2
I do not have Rust installed

Best regards,
Ivan

**Comment by gvozdvmozgu** [comment]
Which config are you using?

**Comment by ikhudur** [comment]
My apologise, what do you mean by what config I am using?

**Comment by gvozdvmozgu** [comment]
Do you have a .sqlfluff file

**Comment by ikhudur** [comment]
Yes, the .sqlfluff looks like this:

```
[sqlfluff]
dialect = databricks
templater = dbt
rules = all
exclude_rules = ST06
max_line_length = 150

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:dbt]
project_dir = ./
profiles_dir = .
profile = db
target = dev

[sqlfluff:rules]
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = upper

[sqlfluff:rules:capitalisation.literals]
extended_capitalisation_policy = upper

[sqlfluff:rules:convention.count_rows]
prefer_count_1 = True
```

**Comment by louisjoecodes** [comment]
Hey @ikhudur, unfortunately sqruff doesn't support dbt. Definitely might be worth checking out what we are building over at https://github.com/quarylabs/quary 😊

**Comment by alxsbn** [comment]
@louisjoecodes It's a must have I think :)

**Comment by catkins** [comment]
ah, just ran into this too - yeah +1 for dbt support!

**Comment by benfdking** [comment]
https://x.com/BenFKing/status/1821546414763327796 We're trying to find a way that is fair and just.

**Comment by segoldma** [comment]
+1!

**Comment by jordandakota** [comment]
It works perfectly fine with dbt but for the {{. I can't find a way to avoid adding a space between the brackets without just disabling the rule.

**Comment by benfdking** [comment]
This has been a while coming, but it's finally here. I am going to put a big disclaimer on this first release. There are still many issues, but if you try and report any bugs, we'll try to fix them. 

For instructions, first make sure you have a venv, then:

```
pip install 'sqruff[dbt]'
pip install regex
```

```
sqruff lint models
```


There's a bug I already noticed and there are issues I know may come up: 

* [ ] need to pip install regex
* [ ] on mac osx has to build wheel and is very slow
* [ ] lack of the jinja rule which doesn't format it yet
* [ ] ...

**Comment by benfdking** [comment]
> Just add uv in front of pip install and most of your very slow builds disappear!

As much as I love `uv`, it doesn't yet have a way of making rust compile jobs faster. :P

**Comment by iRod3s** [comment]
@benfdking First of all, ty for adding dbt support <3

I have been trying to make this release to work, but unfortunately, I keep getting the following error:

`sqruff: error while loading shared libraries: libpython3.12.so.1.0: cannot open shared object file: No such file or directory`

Do you know what can be causing the error? I am running sqruff on Python3.12 inside a virtual environment

**Comment by ikhudur** [comment]
@benfdking Thank you very much!

I have tried it but I can not get it to work.
When I run `sqruff lint model.sql`, I get the following error:

`thread '<unnamed>' panicked at crates/lib/src/core/linter/core.rs:173:58:
called `Result::unwrap()` on an `Err` value: SQLFluffUserError { value: "Failed to template file model.sql with error SQLFluffUserError { value: \"Python templater error: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError(\\\"No module named 'dbt.mp_context'\\\"), traceback: Some(\\\"Traceback (most recent call last):\\\\n  File \\\\\\\"/home/my-user/git/dbt-repo/.venv/dbt-cloud/lib/python3.12/site-packages/sqruff/templaters/dbt_templater.py\\\\\\\", line 43, in <module>\\\\n    import dbt.mp_context\\\\n\\\") }\" }" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/my-user/git/dbt-repo/.venv/dbt-cloud/bin/sqruff", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/my-user/git/dbt-repo/.venv/dbt-cloud/lib/python3.12/site-packages/sqruff/main.py", line 8, in main
    status = run_cli(sys.argv[1:])
             ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: SQLFluffUserError { value: "Failed to template file model.sql with error SQLFluffUserError { value: \"Python templater error: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError(\\\"No module named 'dbt.mp_context'\\\"), traceback: Some(\\\"Traceback (most recent call last):\\\\n  File \\\\\\\"/home/my-user/git/dbt-repo/.venv/dbt-cloud/lib/python3.12/site-packages/sqruff/templaters/dbt_templater.py\\\\\\\", line 43, in <module>\\\\n    import dbt.mp_context\\\\n\\\") }\" }" }`

I am using dbt cloud and have configured dbt cloud cli in VSCode

Best regards,
Ivan

**Comment by jochemvandooren** [comment]
Great to see that you are working on it! 🙌 Tried it out a little bit, but it seems to fail on disabled models. 

Do you have any idea on when this feature is expected to be released officially?
